name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker Images
      run: |
        docker push myapp-web-app:latest
        docker push myapp-ml-client:latest

    - name: Deploy to server
      run: |
        ssh -i /path/to/key.pem your-user@your-server 'docker-compose -f /path/to/docker-compose.yml up -d'
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
