name: Continuous Integration

on:
  push:
    branches: [ henry ]
  pull_request:
    branches: [ henry ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./machine-learning-client/requirements.txt
        pip install -r ./web-app/requirements.txt
    - name: Lint with Pylint
      run: |
        pip install pylint
        pylint **/*.py

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest

    - name: Build Docker Images
      run: |
        docker build -t myapp-web-app ./web-app/
        docker build -t myapp-ml-client ./machine-learning-client/
